### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read property 'map' of undefined

### ISSUE THREAD

**Issue by jaydson** [braziljs/newslleter-tool#17]
Sometimes, and I can't figure it out why, we're unable to see the list of items.
Looking at the console we have the following error:  
`Uncaught (in promise) TypeError: Cannot read property 'map' of undefined`

It seems that it's something related to the categories.

**Comment by RenatoSiqueira** [comment]
PR#15 resolves this.

**Comment by jaydson** [comment]
Great, PR #15 was just merged.
Thanks!
