### ISSUE TITLE
[ERROR] - Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by luan0ap** [braziljs/newslleter-tool#19]
Depois de instalar todas a dependencia necessária e rodar o projeto ele está retornando este erro, para o arquivo `github.js` na linha `const { apiUrl, reposConfig } = require('../constants')`, require não é suportado pelos navegadores, e pelo o que vi não há nenhum transpiler no projeto. 

O mesmo para o arquivo `index.js` onde se tem a declaração da classe `Github` mas ela não é instânciada e muito menos chamada: `let url = Github.urls.inCampaign`

Pensei que isso poderia ser intencional, por isso resolvir abrir uma Issue antes de mandar o PR

**Comment by RenatoSiqueira** [comment]
De fato não é.
To subindo um PR.

**Comment by jaydson** [comment]
Fixed by #20

**Comment by jaydson** [comment]
Valeu pelo report @luan0ap !
